version: '3.6'

services:
  client:
    image: node:12-slim
    container_name: vue-client-tester
    working_dir: /client
    volumes:
      - /client/node_modules/
      - ./client:/client      
    command: npm run test-integration-headless