version: '3.6'

services:
  client:
    image: vue-client:latest
    build: ./client
    container_name: vue-client-tester
    working_dir: /client
    volumes:
      - /client/node_modules/
      - ./client:/client      
    command: npm run-script test-integration-headless