  
name: Jira TODO

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Jira TODO
        uses: atlassian/gajira-todo@master
        with:
          project: GA
          issuetype: Task
          description: Created automatically via GitHub Actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
